#!/usr/bin/env python3
import argparse
import sys


def upload(project_id, files):
    print('Not yet implemented!')


def parse_args(argv):
    parser = argparse.ArgumentParser(
        prog=argv[0],
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    sub = parser.add_subparsers(help='commands', dest='command')
    upload = sub.add_parser(
        'upload',
        help='upload files',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    upload.add_argument('project_id',
                        help='project ID on Big Local News platform')
    upload.add_argument('files', help='list of files to upload')
    return parser.parse_args(argv[1:])


if __name__ == '__main__':
    args = parse_args(sys.argv)
    {
        'upload': lambda: upload(args.project_id, args.files),
    }[args.command]()
